release-primary:
    ARG_BUILD_EXTRA_ARGS="" just _release-raw

release-gb300:
    ARG_BUILD_EXTRA_ARGS='--build-arg SGLANG_IMAGE_TAG=dev-arm64-cu13-20251116 --build-arg ENABLE_BLACKWELL_BUILD=1 --build-arg ENABLE_CUDA_13=1' just _release-raw

_release-raw:
    #!/bin/bash
    set -euxo pipefail
    cd ..

    VERSION="$(cat docker/version.txt | tr -d '\n')"

    docker build -f docker/Dockerfile . $ARG_BUILD_EXTRA_ARGS -t radixark/miles:$VERSION
    docker push radixark/miles:$VERSION

    docker tag radixark/miles:$VERSION radixark/miles:latest
    docker push radixark/miles:latest
